name = "v20251104"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

#[[kv_namespaces]]
#binding = "KV"			#KV绑定名默认不可修改

#id = ""				#KV数据库id

# 1. 连接到你的KV命名空间
kv_namespaces = [
  { binding = "KV", id = "82918e64ac514467aa18b9230c2ff064" }
]
# 2. 部署到workers.dev（最简单的方式）
workers_dev = true
